AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  videocloudffmpeg:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: ffmpeg_lambda.handler
      Runtime: python3.9
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 120
      Role: "arn:aws:iam::169776285963:role/lambda-to-s3-full-access"
      Layers:
        - "arn:aws:lambda:us-east-1:169776285963:layer:ffmpeg:1"
